name: Docker publish development versions

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Add SHORT_SHA env property with commit short sha
        id: vars
        run: |
          calculatedSha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "::set-output name=short_sha::$calculatedSha"
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: axeleroy/self-host-planning-poker:development,axeleroy/self-host-planning-poker:${{ steps.vars.outputs.short_sha }}
